-- 코드를 입력하세요
SELECT b.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY,
SUM (c.SALES * a.PRICE ) as TOTAL_SALES
FROM BOOK a JOIN AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES c on a.BOOK_ID = c.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY  b.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY
ORDER BY a.AUTHOR_ID ASC, a.CATEGORY DESC