-- 코드를 입력하세요
SELECT B.BOOK_ID AS BOOK_ID,
       A.AUTHOR_NAME AS AUTHOR_NAME,
       date_format(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE 
from BOOK B inner join AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
order by B.PUBLISHED_DATE;